REQUIRED_PACKAGE_PATHS = (
    "run.sh",
    "README.md",
    "config/config.yaml",
    "config/config.example.yaml",
    "config/.env.example",
    ".gitignore",
    "manifest.json",
    "benchmark_suite",
)

RUNTIME_SOURCE_EXPORT_DIR = "src"

REQUIRED_RUNTIME_SOURCE_PATHS = (
    "src/bin/payskills-run",
    "src/bin/payskills-agent",
    "src/bin/payskills-judge",
    "src/bin/payskills-diff",
    "src/bin/payskills-result",
    "src/payskills_runtime/__init__.py",
    "src/payskills_runtime/agent/__init__.py",
    "src/payskills_runtime/agent/artifacts.py",
    "src/payskills_runtime/agent/cli.py",
    "src/payskills_runtime/agent/doctor.py",
    "src/payskills_runtime/agent/drive.py",
    "src/payskills_runtime/agent/events/__init__.py",
    "src/payskills_runtime/agent/events/claude.py",
    "src/payskills_runtime/agent/events/hermes.py",
    "src/payskills_runtime/agent/events/normalizers.py",
    "src/payskills_runtime/agent/events/openclaw.py",
    "src/payskills_runtime/agent/events/parsing.py",
    "src/payskills_runtime/agent/events/schema.py",
    "src/payskills_runtime/agent/events/stdout.py",
    "src/payskills_runtime/agent/evidence.py",
    "src/payskills_runtime/agent/invocation.py",
    "src/payskills_runtime/agent/prompts.py",
    "src/payskills_runtime/agent/providers/__init__.py",
    "src/payskills_runtime/agent/providers/commands.py",
    "src/payskills_runtime/agent/providers/config.py",
    "src/payskills_runtime/agent/providers/sessions.py",
    "src/payskills_runtime/agent/providers/traces.py",
    "src/payskills_runtime/agent/skills.py",
    "src/payskills_runtime/agent/turn_records.py",
    "src/payskills_runtime/agent/usage/__init__.py",
    "src/payskills_runtime/agent/usage/contract.py",
    "src/payskills_runtime/agent/usage/sources.py",
    "src/payskills_runtime/agent/visible_output.py",
    "src/payskills_runtime/common/benchmark_suite_runtime.py",
    "src/payskills_runtime/common/manifest_contract.py",
    "src/payskills_runtime/config/__init__.py",
    "src/payskills_runtime/config/contract.py",
    "src/payskills_runtime/config/defaults.py",
    "src/payskills_runtime/config/format.py",
    "src/payskills_runtime/config/summary.py",
    "src/payskills_runtime/diff/__init__.py",
    "src/payskills_runtime/docker/commands.py",
    "src/payskills_runtime/docker/host.py",
    "src/payskills_runtime/docker/images.py",
    "src/payskills_runtime/doctor/__init__.py",
    "src/payskills_runtime/doctor/checks.py",
    "src/payskills_runtime/doctor/guidance.py",
    "src/payskills_runtime/doctor/output.py",
    "src/payskills_runtime/execution/__init__.py",
    "src/payskills_runtime/execution/container_scripts.py",
    "src/payskills_runtime/execution/dry_run.py",
    "src/payskills_runtime/execution/orchestrator.py",
    "src/payskills_runtime/execution/preflight.py",
    "src/payskills_runtime/execution/run_output.py",
    "src/payskills_runtime/execution/run_paths.py",
    "src/payskills_runtime/execution/runtime_checks.py",
    "src/payskills_runtime/execution/runtime_env.py",
    "src/payskills_runtime/execution/summary.py",
    "src/payskills_runtime/export/builder.py",
    "src/payskills_runtime/export/layout.py",
    "src/payskills_runtime/export/package.py",
    "src/payskills_runtime/judge/__init__.py",
    "src/payskills_runtime/judge/transport.py",
    "src/payskills_runtime/platform/sandbox.py",
    "src/payskills_runtime/platform/task_instance.py",
    "src/payskills_runtime/result/__init__.py",
    "src/payskills_runtime/result/contract.py",
    "src/payskills_runtime/result/scoring.py",
    "src/payskills_runtime/runner.py",
    "src/payskills_runtime/task_instance/__init__.py",
    "src/payskills_runtime/task_instance/contract.py",
    "src/payskills_runtime/task_instance/execution.py",
    "src/payskills_runtime/task_instance/invocation.py",
    "src/payskills_runtime/task_instance/requirements.py",
    "src/payskills_runtime/task_instance/runner.py",
    "src/docker/agent-layer/install_agents.sh",
    "src/docker/agent-layer/doctor.sh",
)

EXPORT_TEMPLATE_FILES = (
    "run.sh",
    ".gitignore",
    "README.md",
)

EXPORT_CONFIG_TEMPLATE_FILES = (
    "config.yaml",
    "config.example.yaml",
    ".env.example",
)

RUNTIME_KIT_DIRS = ("bin", "payskills_runtime", "docker")
RUNTIME_KIT_FILES = ("README.md",)
